version: "3"

services:
    web-server:
        image: natsuwumi/random-website-redirect:latest
        volumes:
          - ./urls.json:/srv/random-website-redirect/urls.json
        env_file:
          - .env
        networks:
          - proxy_net

networks:
  proxy_net:
    external: true